name: Accessibility Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pa11y:
    steps:
      - name: Start preview server
        working-directory: 12
        runs: npm run preview -- --host 127.0.0.1 --port 5173 &

      - name: Wait for server
        working-directory: 12
        run: npx wait-on http-get://127.0.0.1:5173

      - name: Run accessibility checks (Light mode)
        working-directory: 12
        run: npx pa11y-ci --config .pa11yci

      - name: Run accessibility checks (Dark mode)
        working-directory: 12
        run: npx pa11y-ci --config .pa11yci-dark.json